---
development:
  cloud_name: emprestaufscar
  api_key: '842347469714227'
  api_secret: TQRwxoYwo8uTsZxa7irEkl7eA8c
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: emprestaufscar
  api_key: '842347469714227'
  api_secret: TQRwxoYwo8uTsZxa7irEkl7eA8c
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: emprestaufscar
  api_key: '842347469714227'
  api_secret: TQRwxoYwo8uTsZxa7irEkl7eA8c
  enhance_image_tag: true
  static_file_support: false
